# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('qualification', models.CharField(max_length=20)),
                ('years', models.BigIntegerField()),
                ('district', models.CharField(max_length=15)),
                ('data_number', models.BigIntegerField()),
            ],
        ),
    ]
